dist: trusty
sudo: required

language: node_js
node_js:
  - 8
  
branches:
  only:
  - master

addons:
  chrome: stable

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:single-run
